.TH VEGA 1 2023-03-12
.SH NAME
vega - a simpler and faster fetch written in c and POSIX sh
.SH SYNOPSIS
.B vega

.B vega
[options] 
.SH DESCRIPTION
vega is a command line system information tool designed to be simpler and by extension, faster than neofetch.
.SH OPTIONS
.TP
.B --model
    Displays device mode and exits

.B --cpu
    Displays cpu and exits

.B --gpu
    Displays the first gpu detected and exits

.B --ram
    Displays memory info and exits

.B --disk
    Displays free space / total space of the root partition

.B --res
    Displays the screen resolution of the first monitor

.B --os
    Displays the name of the operating system

.B --pkg
    Displays the number of packages

.B --wm
    Displays the current window manager

.B --term
    Displays the current terminal

.B --shell
    Displays the current shell

.B --ip
    Displays the current device's local ip address

.B --version
    Displays the version and license information

.B --help
    Displays this help message
    
.SH AUTHORS
\fBvega\fP was written by Frank Tao

.SH REPORTING BUGS
Please open an issue at https://github.com/bloodandcoffee/vega